[www]
pm = dynamic
pm.max_children = 20
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 5
pm.max_requests = 500

; Catch stderr output to docker logs
catch_workers_output = yes
decorate_workers_output = no
